<?php
if ($this->flashSession->output()) { ?>
    <div class="errorMessage"><?php echo $this->flashSession->output() ?></div>
<?php } ?>

<div class="col-sm-6" style="margin-left: 25%;">
    <form role="form" action="/sign-up" method="post">
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1"
                   placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Sign up</button>
    </form>
</div>