<div class="col-sm-6">
    <div class="row">
        <p>Welcome</p>

        <p><a href="/admin/new-post">New post</a></p>
    </div>

    <div class="row">
       <?php
        foreach($posts as $post){?>
            <p><?php echo $post->getTitle()?></p>
            <p><?php echo $post->getDescription()?></p>
            <p><?php echo $post->getDate()?></p>
            <p>
                <a href="/admin/post/edit/<?php echo $post->getId()?>" class="alert alert-success">Edit</a>
                <a href="/admin/post/delete/<?php echo $post->getId()?>" class="alert alert-danger">Delete</a>
            </p>
            <hr>
        <?php }?>
    </div>
</div>