<?php
if ($this->flashSession->output()) { ?>
    <div class="errorMessage"><?php echo $this->flashSession->output() ?></div>
<?php } ?>

<div class="col-sm-6" style="margin-left: 25%;">
    <form role="form" action="/admin/new-post" method="post">
        <div class="form-group">
            <label>Title</label>
            <input type="text" name="title" class="form-control"
                   placeholder="Enter title">
        </div>
        <div class="form-group">
            <label>Description</label>
            <input type="text" name="description" class="form-control"
                   placeholder="Enter some description">
        </div>
        <button type="submit" class="btn btn-default">Post</button>
    </form>
</div>