<?php
if ($this->flashSession->output()) { ?>
    <div class="errorMessage"><?php echo $this->flashSession->output() ?></div>
<?php } ?>

<div class="col-sm-6" style="margin-left: 25%;">
    <form role="form" action="/admin/issue/edit/<?php echo $post->getId() ?>" method="post">
        <div class="form-group">
            <label>Title</label>
            <input type="text" name="title" class="form-control"
                   value="<?php echo $post->getTitle() ?>">
        </div>
        <div class="form-group">
            <label>Description</label>
            <input type="text" name="description" class="form-control"
                   value="<?php echo $post->getDescription() ?>">
        </div>
        <button type="submit" class="btn btn-default">Edit</button>
    </form>
</div>